[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mitmflow"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "connect-python",
    "protobuf",
    "mitmproxy",
    "hypercorn",
]
